### ISSUE TITLE
WSL Installation Issues

### ISSUE THREAD

**Issue by ghostlypi** [Avedati/AbhiScript2#1]
When I run the make with appropriate permissions:
```
rustc src/main.rs -o bin/abhiscript_inner
make: rustc: Command not found
make: *** [Makefile:6: all] Error 127
```

**Comment by Avedati** [comment]
You must have rust installed on your system to install AbhiScript on Windows.

**Comment by ghostlypi** [comment]
You should add that to the install instructions:
````
sudo apt install rust
````
this should work on all systems except Mac. Also your wsl instructions work for some linux distros as well.
